import EmployeeSidebarServer from "@/_components/EmployeeSidebarServer"
import { Toaster } from "sonner"
import '@/_styles/globals.css'
import DashboardHeader from './DashboardHeader';

import { getScheduleCount } from "@/_lib/partials/getScheduleCount";

export const metadata = {
  title: "Employee | Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({ children }) {
  const scheduleCount = await getScheduleCount()

  return (
    <div className="flex h-screen">
      <EmployeeSidebarServer scheduleCount={scheduleCount} />

      <div className="flex-1 flex flex-col"> 
        <Toaster position="top-right" richColors expand duration={3000} closeButton toastOptions={{
            className: "rounded-lg shadow-lg border border-slate-200",
            style: { fontSize: "14px", padding: "12px 16px" },
          }}
        />
        <DashboardHeader />
        <main className="flex-1 overflow-y-auto p-6 bg-slate-100">
          {children}
        </main>
      </div>
    </div>
  )
}
