import '@/_styles/employees.css'

export const metadata = {
  title: "Employee | Dashboard",
  description: "Generated by create next app",
};

import { Toaster } from "sonner"
import DashboardHeader from './DashboardHeader';

import SidebarBase from "@/_components/sidebar/SidebarBase";
import { employeeMenu } from "@/_components/sidebar/content/employee.menu";

import { getCurrentUser } from "@/_lib/auth";
import { getScheduleCount } from "@/_lib/partials/getScheduleCount";
import { getChangeShiftCount } from '@/_lib/partials/getChangeShiftCount';

export default async function DashboardLayout({ children }) {

  const scheduleCount = await getScheduleCount()
  const csCount = await getChangeShiftCount()
  const user = await getCurrentUser()

  return (
    <div className="flex h-screen">
      <SidebarBase menu={employeeMenu(csCount, scheduleCount)} user={user} />

      <div className="flex-1 flex flex-col"> 
        <Toaster position="top-right" richColors expand duration={3000} closeButton toastOptions={{
            className: "rounded-lg shadow-lg border border-slate-200",
            style: { fontSize: "14px", padding: "12px 16px" },
          }}
        />
        <DashboardHeader />
        <main className="flex-1 overflow-y-auto p-6 bg-slate-100">
          {children}
        </main>
      </div>
    </div>
  )
}
