import '@/_styles/admin.css'
import '@/_styles/utilities.css'

export const metadata = {
  title: "Admin | Settings",
  description: "Generated by create next app",
};

import { DashboardHeader } from '../../DashboardHeader';
import { SettingsTabs } from './SettingsTabs';

export default async function DashboardLayout({ children }) {
  return (
    <div>
        <DashboardHeader title="Settings" subtitle="See your style for management content right here"/>
        <SettingsTabs />
        {children}
    </div>
  );
}
