import '@/_styles/admin.css'

export const metadata = {
  title: "Admin | Dashboard",
  description: "Generated by create next app",
};

import { ReactQueryProvider } from '@/_context/Query-Provider';
import { ToastProvider } from '@/_context/Toast-Provider';
import { ConfirmDialog } from "@/_components/ui/Confirm";

import SidebarBase from '@/_components/sidebar/SidebarBase';
import { adminMenu } from '@/_components/sidebar/content/admin.menu';

import { getCurrentUser } from '@/_lib/auth';

export default async function DashboardLayout({ children, action }) {

  const user = await getCurrentUser()

  return (
    <div className="flex h-screen">
      <SidebarBase menu={adminMenu} user={user} />

      <div className="flex-1 flex flex-col">
        {action}

        <main className="flex-1 overflow-y-auto px-[15px] py-[12px] bg-slate-100">
          <ReactQueryProvider>
            <ToastProvider><ConfirmDialog />
              {children}
            </ToastProvider>
          </ReactQueryProvider>
        </main>
      </div>
    </div>
  );
}
