import SidebarServer from "@/_components/AdminSidebarServer"
import '@/_styles/globals.css'
import { ReactQueryProvider } from '@/_context/Query-Provider';
import { ToastProvider } from '@/_context/Toast-Provider';
import { ConfirmDialog } from "@/_components/ui/Confirm";

export const metadata = {
  title: "Admin | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children, action }) {
  return (
    <div className="flex h-screen">
      <SidebarServer />

      <div className="flex-1 flex flex-col">
        {action}

        <main className="flex-1 overflow-y-auto p-[13px] bg-slate-100">
          <ReactQueryProvider>
            <ToastProvider><ConfirmDialog />
              {children}
            </ToastProvider>
          </ReactQueryProvider>
        </main>
      </div>
    </div>
  );
}
